### ISSUE TITLE
Crashing Game on Start Screen

### ISSUE THREAD

**Issue by vladbsch** [cerebellum42/BuildingAIChanger#2] opened 2017-02-23 20:33 UTC
Both ItemClass Changer and AI Changer crash the game showing an error message saying file sources of many other mods (like Building Themes, Control Building, Environment Changer, RICO, etc) could not be found. 
Game is updated to Natural Disasters
![error](https://cloud.githubusercontent.com/assets/25989852/23277818/0bdbbc18-f9ee-11e6-8c29-afcb04aca5da.jpg)

**Comment by stkfd** [comment] 2017-02-23 21:08
"Source files not found" messages should not have any impact usually, I don't think that's related. I get those too, but I'm not getting any crashes

A few followup questions:

1. There are two versions of the AI changer on steam (one is an older spinoff by Snow_Cat, the updates in there were merged back into the original one though). Can you make sure you are subscribed to the one on my account?

2. How have you tested this? Disable only this mod -> restart -> works, Enable only this mod -> restart -> doesn't work? Ideally first while having all your other mods enabled, then _just_ this mod with no other mods enabled

I'm not experiencing any issues currently, with the game fully updated but without Natural Disasters. I think it's fairly unlikely Natural Disasters would cause a crash on startup, since the major code changes are always in the free updates as well, but who knows.

Since I can't reproduce the issue currently, you'll have to help troubleshooting a bit

**Comment by vladbsch** [comment] 2017-02-23 22:55
Ok, really sorry for wasting your time with a clumsy mistake of mine. I checked the folder of the ItemClass changer and there was a duplicate of the .dll file. Deleted it and problem solved. Really sorry, but thanks for promptly replying, that was really great of you. One of the main reasons I play this game is for aesthetics, I prioritize the visuals and design of the city, your work is really great and crucial to allow that feature in the game, thank you very much for your great mods! 

ps.: and of course, you can delete this issue thread as it is pointless

**Comment by stkfd** [comment] 2017-02-23 23:03
No problem, glad you worked your problem out!

**Closed as completed by stkfd** 2017-02-23 23:03 UTC
